backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/img'

collections:
  - name: 'Publications'
    label: 'Publication'
    files:
      - label: 'Publications'
        name: 'publications'
        file: '_data/publications.yml'
        fields:
          - label: 'Publications'
            name: 'items'
            widget: 'list'
            fields:
              - label: 'Content'
              - name: 'content'
              - widget: 'string'
