backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/img'

collections:
  - name: 'Content'
    label: 'Content'
    files:
      - label: 'Publications'
        name: 'Publications'
        file: '_data/publications.yml'
        fields:
          - label: 'Publications'
            name: 'items'
            widget: 'list'
            fields:
              - label: 'Content'
              - name: 'content'
              - widget: 'string'

      - label: 'Conferences'
        name: 'Conferences'
        file: '_data/conferences.yml'
        fields:
          - label: 'Conferences'
            name: 'items'
            widget: 'list'
            fields:
              - { label: 'Authors', name: 'authors', widget: 'string' }
              - { label: 'Year', name: 'year', widget: 'string' }
              - { label: 'Content', name: 'content', widget: 'string' }
              - { label: 'Conference', name: 'conference', widget: 'string' }
              - { label: 'Location', name: 'location', widget: 'string' }
              - { label: 'Date', name: 'date', widget: 'string' }
